# Generated by Django 5.0.6 on 2024-06-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teacher_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='classes',
            new_name='clas',
        ),
    ]
